name: Python Linting

on: [pull_request]

jobs:
  lint_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: pip install flake8
    # Note: flake8 picks up project-wide configuration options from 'setup.cfg' in SCT's root directory
    - name: Lint with flake8
      run: |
      export HEAD_SHA=${{ github.event.pull_request.head.sha }}
      export BASE_SHA=$(git merge-base master $HEAD_SHA)
      git diff $BASE_SHA..$HEAD_SHA | flake8 --diff

