name: Python Linting

on:
  pull_request_target:

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  lint_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: pip install flake8 lintly==0.5.0
    # Note: flake8 picks up project-wide configuration options from 'setup.cfg' in SCT's root directory
    - name: view the PR number
      run: |
        echo "PR number = ${{ github.event.pull_request.number }}"
        echo "PR number = ${{ env.PR_NUMBER }}"
    - name: Lint with flake8
      run: flake8 | lintly --use-checks --fail-on new --exit-zero --no-post-status --commit-sha ${{ github.sha }} --pr ${{ github.event.number }} --log
      env:
        LINTLY_API_KEY: ${{ secrets.GITHUB_TOKEN }}